name: Selenium Tests

on:
  schedule:
    - cron: '0 3,11,17 * * *'  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager pandas

      - name: Run Aldenham School tests
        run: pytest test_AldenhamAnswers.py --tb=short --junitxml=results.xml

      - name: Run Alleyns School tests
        run: pytest test_AlleynsAnswers.py --tb=short --junitxml=results.xml

      - name: Run Christs School tests
        run: pytest test_ChristsAnswers.py --tb=short --junitxml=results.xml

      - name: Run Dulwich School tests
        run: pytest test_DulwichAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Eltham College tests
        run: pytest test_ElthamCollegeAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Emanuel College tests
        run: pytest test_EmanuelAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Forest School tests
        run: pytest test_ForestAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Kent College tests
        run: pytest test_KentCollegeAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Kings College tests
        run: pytest test_KingsCollege.py  --tb=short --junitxml=results.xml

      - name: Run Merchant Taylor School tests
        run: pytest test_MerchantTaylorsAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Reigate Grammar School tests
        run: pytest test_ReigateGrammarAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Sevenoaks School tests
        run: pytest test_SevenoaksAnswers.py  --tb=short --junitxml=results.xml

      - name: Run John lyon School tests
        run: pytest test_JohnLyonAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Perse Upper School tests
        run: pytest test_PerseUpperAnswers.py  --tb=short --junitxml=results.xml

      - name: Run Haberdasshers School tests
        run: pytest test_HaberdashersAnswers.py  --tb=short --junitxml=results.xml
            
      # Upload screenshots
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png


      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
